version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/web
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run: npm run test
