name: Vue End-to-end tests
on:
  push:
    branches:
      - master
    paths:
      - 'web/*'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          serve: npm run serve
          wait-on: http://localhost:8080